[tools]
rust = "latest"
node = "lts"
deno = "latest"
npm = "latest"
pnpm = "latest"
claude-code = "latest"
"npm:@anthropic-ai/sandbox-runtime" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:@olrtg/emmet-language-server" = "latest"
"npm:css-variable-ls" = "latest"
"npm:some-sass-language-server" = "latest"
"npm:tombi" = "latest"
"cargo:bacon" = "latest"
"cargo:cargo-expand" = "latest"
"cargo:cargo-sweep" = "latest"
"cargo:https://github.com/estin/simple-completion-language-server" = "latest"
"cargo:typst-cli" = "latest"
"cargo:https://github.com/itsjunetime/tdf.git" = "latest"
"github:Myriad-Dreamin/tinymist" = "latest"
go = "latest"
"go:github.com/mattn/efm-langserver" = "latest"
ruby = "latest"
"gem:ruby-lsp" = "latest"
"gem:rubocop" = "latest"
"npm:@antfu/ni" = "latest"
"npm:react-devtools" = "latest"
fzf = "latest"
ghq = "latest"
"go:github.com/d-kuro/gwq/cmd/gwq" = "latest"
starship = "latest"
helix = "latest"
yazi = "latest"
fd = "latest"
jq = "latest"
resvg = "latest"
lazygit = "latest"
gh = "latest"
ripgrep = "latest"
watchexec = "latest"
"cargo:rip2" = "latest"

[settings]
lockfile = true
