[tools]
rust = "latest"
node = "latest"
deno = "latest"
npm = "latest"
pnpm = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@anthropic-ai/sandbox-runtime" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:@olrtg/emmet-language-server" = "latest"
"npm:css-variable-ls" = "latest"
"npm:stylelint-lsp" = "latest"
"npm:tombi" = "latest"
"cargo:bacon" = "latest"
"cargo:cargo-expand" = "latest"
"cargo:cargo-make" = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:cargo-sweep" = "latest"
"cargo:https://github.com/estin/simple-completion-language-server" = "latest"
"cargo:typst-cli" = "latest"
"cargo:https://github.com/itsjunetime/tdf.git" = "latest"
"github:Myriad-Dreamin/tinymist" = "latest"
"npm:@antfu/ni" = "latest"

[settings]
lockfile = true
