[env]
HELIX_RUNTIME = "~/dev/github.com/helix-editor/helix/runtime"

[tools]
rust = { version = "latest", profile = "default" }
rust-analyzer = "latest"
node = "lts"
deno = "latest"
pnpm = "latest"
claude-code = "latest"
"npm:@anthropic-ai/sandbox-runtime" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:@olrtg/emmet-language-server" = "latest"
"npm:some-sass-language-server" = "latest"
"tombi" = "latest"
"cargo:bacon" = "latest"
"cargo:cargo-expand" = "latest"
"cargo:cargo-sweep" = "latest"
"cargo:https://github.com/estin/simple-completion-language-server" = "rev:c48876d02e17fad827e30d26696ad17b111ffa68"
"typst" = "latest"
"tinymist" = "latest"
"cargo:https://github.com/itsjunetime/tdf.git" = "rev:7b9e1462da6d75d65cd1a3f5f263fda1046bed7e" # v0.5.0
go = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:github.com/mattn/efm-langserver" = "latest"
ruby = "latest"
"gem:ruby-lsp" = "latest"
"gem:rubocop" = "latest"
"npm:@antfu/ni" = "latest"
"npm:react-devtools" = "latest"
fzf = "latest"
ghq = "latest"
"go:github.com/d-kuro/gwq/cmd/gwq" = "latest"
starship = "latest"
yazi = "26.1.22"
fd = "latest"
jq = "latest"
resvg = "latest"
lazygit = "latest"
lazydocker = "latest"
gh = "latest"
ripgrep = "latest"
watchexec = "latest"
# 最新のvue-language-serverを同じパスで参照できるようにシンボリックリンクを作成
"npm:@vue/language-server" = { version = "latest", postinstall = "mkdir -p ~/.local/share/lsp && ln -sfn $MISE_TOOL_INSTALL_PATH/lib/node_modules/@vue/language-server ~/.local/share/lsp/vue-language-server" }
vp = "latest"

[hooks]
postinstall = "cd $(dotfiles path) && mise lock -g"

[tasks.build_helix]
run = """
  cd "$GHQ_ROOT/github.com/helix-editor/helix" || exit
  cargo install \
    --profile opt \
    --config 'build.rustflags="-C target-cpu=native"' \
    --path helix-term \
    --locked
"""

[settings]
minimum_release_age = "3d"
experimental = true
lockfile = true
