version: 2
# log-file: "/tmp/efm.log"
# log-level: 3
tools:
  stylelint: &stylelint
    lint-command: 'ne stylelint --formatter compact --stdin --stdin-filename ${INPUT}'
    lint-stdin: true
    lint-formats:
      - '%f: line %l, col %c, %m (%t%*[^ ])'
    lint-severity: 1
    format-command: 'ne stylelint --fix --stdin --stdin-filename ${INPUT}'
    format-stdin: true
    root-markers:
      - stylelint.config.js
      - stylelint.config.cjs
      - .stylelintrc
      - .stylelintrc.json

  biome-format: &biome-format
    format-command: 'ne biome check --no-errors-on-unmatched --files-ignore-unknown=true --write --stdin-file-path ${INPUT}'
    format-stdin: true
    root-markers:
      - biome.json
      - biome.jsonc

  oxfmt: &oxfmt
    format-command: 'ne oxfmt --stdin-filepath ${INPUT}'
    format-stdin: true
    root-markers:
      - .oxfmtrc.json
      - .oxfmtrc.jsonc
      - oxfmt.config.ts

languages:
  typescript:
    - <<: *biome-format
    - <<: *oxfmt
  typescriptreact:
    - <<: *biome-format
    - <<: *oxfmt
  javascript:
    - <<: *biome-format
    - <<: *oxfmt
  javascriptreact:
    - <<: *biome-format
    - <<: *oxfmt
  svelte:
    - <<: *biome-format
    - <<: *oxfmt
  html:
    - <<: *biome-format
    - <<: *oxfmt
  css:
    - <<: *stylelint
    - <<: *biome-format
    - <<: *oxfmt
  scss:
    - <<: *stylelint
    - <<: *oxfmt
  json:
    - <<: *biome-format
    - <<: *oxfmt
  jsonc:
    - <<: *biome-format
    - <<: *oxfmt
  yaml:
    - <<: *oxfmt
  markdown:
    - <<: *oxfmt
